version: '3.9'

services:
#mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
  
  #nodejs api service container
  api:
    build: .
    ports:
      - 4000:4000
    volumes:
      - .:/app
    environment:
      PORT: 4000
      DB_URL: mongodb://mongo_db:27017/tshirtstore
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}